### ISSUE TITLE
Issue with VL805 USB 3.0 Controller not found.

### ISSUE THREAD

**Issue by dja-dsd** [radxa-build/radxa-cm5-rpi-cm4-io#3]
Running on a Edatec IPC2200 board.  The CM5 does not seem list the usb 3 controller. 

```
$ lspci -nn
0004:40:00.0 PCI bridge [0604]: Rockchip Electronics Co., Ltd RK3588 [1d87:3588] (rev 01)
```

While with the original CM4

```
$ lspci -nn
00:00.0 PCI bridge [0604]: Broadcom Inc. and subsidiaries BCM2711 PCIe Bridge [14e4:2711] (rev 20)
01:00.0 USB controller [0c03]: VIA Technologies, Inc. VL805 USB 3.0 Host Controller [1106:3486] (rev 01)
```
 
Any idea of what is going wrong ?

**Comment by RadxaYuntian** [comment]
Because CM5's USB controller is not connected on the PCIe bus, but directly to the CPU. You should check USB controller with `lsusb`.

**Comment by dja-dsd** [comment]
lsusb only returns devices for the USB2 controller which is fine.

A VL805 is connected to PCIe on the IO board,  which is *not* on the CPU, it is found by the original rpi CM4 module (as per my previous post), but not by CM5.

![image](https://github.com/user-attachments/assets/5b61958d-a769-4f61-854d-5eb7e116d9a1)


Additionaly there's a supsicous entry in the kernel log which doesnt appear with a different IO board.

```
[    9.603499] rk-pcie fe190000.pcie: PCIe Linking... LTSSM is 0x3
[    9.617273] rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up usb-supply from device tree
[    9.617297] rockchip-pm-domain fd8d8000.power-management:power-controller: Looking up usb-supply property in node /power-management@fd8d8000/power-controller failed
```

**Comment by RadxaYuntian** [comment]
We only validated this image against Raspberry Pi CM4 IO Board.

Do you have a schematic of the aforementioned board?

cc @Ken-Vamrs
